spring.application.name=library

#PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/LibraryManagement
spring.datasource.username=admin
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver


#JPA
spring.jpa.hibernate.ddl-auto=update


#Flyway

spring.flyway.enabled=false
spring.flyway.locations=classpath:db/migration


#Spring Security
spring.web.resources.static-locations=classpath:/static/


jwt.expiration=900000

#The JWT key should be in a path variable for security reasons(isn`t because im studying)
jwt.key=fHYr=5LyVD#sVT%Vw@r1uFhnZ@LxjiEVV.~.^17r8nqd9d#!}e,)Tkrnm25dERJYQ%kPJH=}86B]>:MY>.r4mC_D.}v.Q0E_6ece:ty]Y?EQDQ:iT+rPjPfaW:}=K}DHeWQ>^KvhfZsL~k4Gt2WhN*F*%jAYJ%k4L*jWGNQkb+8+At@yLbnR12YaB%g6C%n>^nRiow:y4C^*Bcw0j:n#=yC:jWy@+Xr=fpA+8%*Yp5k]o#Dcx4XMyVJV_Ez)r9ut96^7@Vsx_z0drWT7Wnu+A?A-ZzmmA2DH~:3?q%1HuUiV